name: workflows tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: Dockerfile
    working-directory: 
    steps:
      - user actions/checkout@v2
      - name: Install dependencies
        run: |
        
      - name: Run tests
        run: |
          make