name: workflows tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t minishell .
      - name: Run docker container
        run: docker run minishell
      - name: Run tests
        working-directory: ./tests
        run: |
          make